---
- hosts: localhost
  become: true

  tasks:
 
    - name: create a new droplet
      digital_ocean_droplet:
        state: present
        name: mydroplet
        oauth_token: insertyourtoken
        size: 1gb
        ssh_keys: insert `curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer insertyourtoken" "https://api.digitalocean.com/v2/ac
count/keys"`
        region: ams2
        image: ubuntu-18-04-x64
        wait_timeout: 500
      register: my_droplet

    - debug:
        msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"
