---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Update apt
      apt: update_cache=yes

    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Install Pip3
      raw: apt -y update && apt install -y python3-pip

    - name: Git clone Osmedeus
      git:
        repo: 'https://github.com/j3ssie/Osmedeus.git'
        dest: /opt/Osmedeus
    - name: Installing Osmedeus
      shell: cd /opt/Osmedeus &&  ./install.sh
